import "./Controller/text.controller.mjs"
import "./Controller/message.controller.mjs"
import "./Controller/callback.controller.mjs"
import "./Controller/admin.controller.mjs"
import "./Controller/otherCommands.controller.mjs"